# Generated by Django 6.0.6 on 2026-06-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('date', models.DateField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
