# Generated by Django 6.0.6 on 2026-06-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='date',
            new_name='user_date',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='phone',
            new_name='user_number',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='username',
        ),
    ]
